import { Box } from '@mui/material';
import Head from 'next/head';
import Image from 'next/image';
import styles from '../styles/Home.module.css';
import MyAppbar from '../components/MyAppBar';
import Background from '../public/images/background.jpg';
import dynamic from 'next/dynamic';
import { useEffect } from 'react';
 
const Home = () => {
  const hotjar=dynamic(()=>import('../utils/hostinger'),{ssr:false})
  useEffect(()=>{

  },[])
  
  return (
    

    <div className={styles.container}>
     
      <Head>
        <title>Create Next App</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />

{/* 
        <head>
         <script></script>
  {/* <script src={'../utils/hostinger.js'} defer/>  */}
  
        {/* </head> */}
    {/* <head>    */}
{/*       
   {typeof(window)===undefined ?<script>
{

(function(h,o,t,j,a,r){
    h.hj=h.hj||function(){(h.hj.q=h.hj.q||[]).push(arguments)};
    h._hjSettings={hjid:3192874,hjsv:6};
    a=o.getElementsByTagName('head')[0];
    r=o.createElement('script');r.async=1;
    r.src=t+h._hjSettings.hjid+j+h._hjSettings.hjsv;
    a.appendChild(r);
}
)(window,document,'https://static.hotjar.com/c/hotjar-','.js?sv=')
                  };

      </script>:null}
        </head> */} 
      </Head>
      <MyAppbar />

      <main className={styles.main}>
        <Image src={Background} alt='back' />
        <Box sx={{ backgroundImage: Background, height: 400 }}></Box>
      </main>

      <footer className={styles.footer}>
        <a
          href='https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app'
          target='_blank'
          rel='noopener noreferrer'
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src='/vercel.svg' alt='Vercel Logo' width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  );
};

export default Home;
